# Generated by Django 3.0.5 on 2020-04-07 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0002_auto_20200406_1955'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meals',
            options={'verbose_name': 'Meal', 'verbose_name_plural': 'Meals'},
        ),
        migrations.RenameField(
            model_name='meals',
            old_name='preperation_time',
            new_name='preparation_time',
        ),
    ]
